// Generated by CoffeeScript 1.6.3
var borderWidth, heightBorder, i, widthBorder, _i;

if (borderType === 0) {
  borderWidth = deviceWidth / 80;
} else if (borderType === 1) {
  borderWidth = (deviceWidth / 80) / 1.2;
} else {
  borderWidth = deviceWidth / 64;
}

widthBorder = new Array(n);

heightBorder = new Array(n);

for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
  widthBorder[i] = Ti.UI.createLabel({
    bottom: 0,
    left: pannelSize * i - (borderWidth / 2),
    width: borderWidth,
    height: deviceHeight,
    backgroundColor: colorBorder
  });
  heightBorder[i] = Ti.UI.createLabel({
    bottom: pannelSize * i - (borderWidth / 2),
    left: 0,
    width: deviceWidth,
    height: borderWidth,
    backgroundColor: colorBorder
  });
}
