// Generated by CoffeeScript 1.6.3
var brightness;

brightness = function(color) {
  var colorArray, colorString, i, resultColor, _i;
  colorString = color.substr(1);
  colorArray = new Array(3);
  resultColor = "#";
  for (i = _i = 0; _i < 3; i = ++_i) {
    colorArray[i] = "0x" + (colorString.substr(i * 2, 2));
    resultColor += (colorArray[i] - (-Math.floor((0xff - colorArray[i]) / 64))).toString(16);
    Ti.API.info(colorArray[i] - (-Math.floor((0xff - colorArray[i]) / 64)));
  }
  return resultColor;
};
