// Generated by CoffeeScript 1.6.3
var i, j, label, _i, _j, _k, _l, _m;

label = new Array(n);

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  label[i] = new Array(n);
}

for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
  for (j = _k = 0; 0 <= n ? _k < n : _k > n; j = 0 <= n ? ++_k : --_k) {
    label[i][j] = Ti.UI.createLabel({
      flag: 0,
      bottom: pannelSize * i,
      left: pannelSize * j,
      width: pannelSize,
      height: pannelSize,
      backgroundColor: startColor,
      text: "",
      textAlign: "Ti.UI.TEXT_ALIGNMENT_CENTER",
      verticalAlign: "TEXT_VERTICAL_ALIGNMENT_CENTER",
      font: {
        fontSize: deviceWidth / 4,
        fontFamily: "SimpleDirectionArrows"
      },
      color: colorBackground,
      borderWidth: deviceWidth / 160,
      borderColor: colorBackground
    });
  }
}

for (i = _l = 0; 0 <= n ? _l < n : _l > n; i = 0 <= n ? ++_l : --_l) {
  for (j = _m = 0; 0 <= n ? _m < n : _m > n; j = 0 <= n ? ++_m : --_m) {
    view.add(label[i][j]);
  }
}
