// Generated by CoffeeScript 1.6.3
var colorBackground, colorBorder, goalColor, i, j, mirrorFlag, n, startColor, _i, _j;

colorBorder = "#555";

colorBackground = "#5d8567";

startColor = "#85aa8e";

goalColor = "#855d7b";

n = 5;

mirrorFlag = 0;

Ti.include("property.js");

Ti.include("change.js");

Ti.include("label.js");

Ti.include("clear.js");

Ti.include("border.js");

Ti.include("tapCount.js");

Ti.include("toChange.js");

Ti.include("reset.js");

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
    label[i][j].addEventListener("touchstart", function(e) {
      var x, y, _ref, _ref1, _ref2, _ref3, _ref4;
      _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
      toChange(k, l, k, l - 1, k, l + 1, k - 1, l, k + 1, l);
      if ((0 <= (_ref1 = (tapCountLabel.text - 1) % 8) && _ref1 < 2)) {
        toChange(0, 0);
      }
      if ((2 <= (_ref2 = (tapCountLabel.text - 1) % 8) && _ref2 < 4)) {
        toChange(0, n - 1);
      }
      if ((4 <= (_ref3 = (tapCountLabel.text - 1) % 8) && _ref3 < 6)) {
        toChange(n - 1, 0);
      }
      if ((6 <= (_ref4 = (tapCountLabel.text - 1) % 8) && _ref4 < 8)) {
        return toChange(n - 1, n - 1);
      }
    });
  }
}
