// Generated by CoffeeScript 1.6.3
var clearCount, i, j, pannelSize, _i, _j;

clearCount = 0;

pannelSize = deviceWidth / 5;

for (i = _i = 0; _i < 6; i = ++_i) {
  for (j = _j = 0; _j < 9; j = ++_j) {
    label[i][j].backgroundColor = startColor;
    label[i][j].borderColor = title.backgroundColor;
    label[i][j].color = labelColor;
    if ((0 <= i && i <= 4) && (0 <= j && j <= 4)) {
      if (lflag !== 0) {
        label[i][j + 3].removeEventListener("touchstart", listener);
      }
      label[i][j + 3].flag = 0;
    }
  }
}

Ti.include("clear.js");

Ti.include("change.js");

Ti.include("tapCount.js");

Ti.include("toChange.js");

Ti.include("reset.js");

Ti.include("toTitle.js");

Ti.include("getPosition.js");

Ti.include("timer.js");

Ti.include("stagenumber.js");

titleButton.backgroundColor = title.backgroundColor;

resetButton.backgroundColor = title.backgroundColor;

stagelabel.backgroundColor = title.backgroundColor;

stagelabel.opacity = 1.0;

resetButton.opacity = 1.0;

titleButton.opacity = 1.0;

tapCountLabel.opacity = 1.0;

timerLabel.opacity = 1.0;

if (lflag !== 0) {
  label[5][4].removeEventListener("touchstart", totit);
  label[5][5].removeEventListener("touchstart", restart);
  label[5][6].removeEventListener("touchstart", next);
  clearInterval(timerID);
  timerLabel.text = "00:00";
}

lflag++;

resetButton.fireEvent("touchstart");
