// Generated by CoffeeScript 1.6.3
var push;

push = function(stagenumber) {
  var i, j, _i, _results;
  _results = [];
  for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
    _results.push((function() {
      var _j, _results1;
      _results1 = [];
      for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
        _results1.push(label[i][j].addEventListener("touchstart", function(e) {
          var positionArray, x, y, _ref;
          tapCountLabel.text++;
          _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
          if (clearCount >= n * n) {
            clear(stagenumber);
          }
          return positionArray = [x, y];
        }));
      }
      return _results1;
    })());
  }
  return _results;
};
