// Generated by CoffeeScript 1.6.3
var resetButton;

if (lflag === 0) {
  resetButton = Ti.UI.createLabel({
    text: "RESET",
    font: {
      fontSize: deviceWidth / 9
    },
    color: goalColor,
    top: (deviceHeight - deviceWidth) / 2 - 20,
    left: 0,
    width: deviceWidth / 2,
    height: (deviceHeight - deviceWidth) / 2,
    textAlign: "center",
    verticalAlign: "TEXT_VERTICAL_ALIGNMENT_CENTER",
    backgroundColor: colorBackground,
    opacity: 1.0
  });
  resetButton.addEventListener("touchstart", function(e) {
    var i, j, _i, _results;
    clearCount *= 0;
    count *= 0;
    _results = [];
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
          label[i][j + 3].flag = 0;
          _results1.push(label[i][j + 3].backgroundColor = startColor);
        }
        return _results1;
      })());
    }
    return _results;
  });
  view.add(resetButton);
} else {
  resetButton.color = goalColor;
  resetButton.backgroundColor = title.backgroundColor;
}
