// Generated by CoffeeScript 1.6.3
var borderType, changeFlag, goalColor, i, j, labelColor, listener, mirrorFlag, n, stagenumber, startColor, _i, _j;

title.backgroundColor = "#50000a";

labelColor = "#ff3c55";

startColor = "#21222d";

goalColor = "#3a4aff";

n = 5;

stagenumber = 21;

mirrorFlag = 0;

borderType = 1;

changeFlag = 1;

Ti.include("property.js");

listener = function() {
  var k, x, y, _i, _j, _k, _l, _m, _n, _o, _p, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
  _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
  if ((count - 1) % 4 === 0) {
    for (k = _i = 0, _ref1 = n - x; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; k = 0 <= _ref1 ? ++_i : --_i) {
      toChange(x + k, y);
    }
    for (k = _j = 0; 0 <= y ? _j < y : _j > y; k = 0 <= y ? ++_j : --_j) {
      toChange(n - 1, y - k - 1);
    }
  }
  if ((count - 1) % 4 === 1) {
    for (k = _k = 0, _ref2 = n - y; 0 <= _ref2 ? _k < _ref2 : _k > _ref2; k = 0 <= _ref2 ? ++_k : --_k) {
      toChange(x, y + k);
    }
    for (k = _l = 0, _ref3 = n - x; 0 <= _ref3 ? _l < _ref3 : _l > _ref3; k = 0 <= _ref3 ? ++_l : --_l) {
      toChange(x + k + 1, n - 1);
    }
  }
  if ((count - 1) % 4 === 2) {
    for (k = _m = 0; 0 <= x ? _m <= x : _m >= x; k = 0 <= x ? ++_m : --_m) {
      toChange(x - k, y);
    }
    for (k = _n = 0, _ref4 = n - y; 0 <= _ref4 ? _n < _ref4 : _n > _ref4; k = 0 <= _ref4 ? ++_n : --_n) {
      toChange(0, y + k + 1);
    }
  }
  if ((count - 1) % 4 === 3) {
    for (k = _o = 0; 0 <= y ? _o <= y : _o >= y; k = 0 <= y ? ++_o : --_o) {
      toChange(x, y - k);
    }
    for (k = _p = 0, _ref5 = n - x; 0 <= _ref5 ? _p <= _ref5 : _p >= _ref5; k = 0 <= _ref5 ? ++_p : --_p) {
      toChange(x - k - 1, 0);
    }
  }
  if (clearCount >= n * n) {
    return clear(stagenumber);
  }
};

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
    label[i][j + 3].addEventListener("touchstart", listener);
  }
}
