// Generated by CoffeeScript 1.6.3
var borderType, changeFlag, goalColor, i, j, labelColor, listener, mirrorFlag, n, stagenumber, startColor, _i, _j;

title.backgroundColor = "#b7f4f4";

labelColor = "#f4b7b7";

startColor = "#00b4ff";

goalColor = "#41d921";

n = 5;

stagenumber = 11;

mirrorFlag = 1;

borderType = 0;

changeFlag = 1;

Ti.include("property.js");

listener = function() {
  var x, y, _ref;
  _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
  if ((count - 1) % 16 === 0) {
    toChange(x, y + 1);
  }
  if ((count - 1) % 16 === 1) {
    toChange(x + 1, y + 1);
  }
  if ((count - 1) % 16 === 2) {
    toChange(x + 1, y);
  }
  if ((count - 1) % 16 === 3) {
    toChange(x + 1, y - 1);
  }
  if ((count - 1) % 16 === 4) {
    toChange(x, y - 1);
  }
  if ((count - 1) % 16 === 5) {
    toChange(x - 1, y - 1);
  }
  if ((count - 1) % 16 === 6) {
    toChange(x - 1, y);
  }
  if ((count - 1) % 16 === 7) {
    toChange(x - 1, y + 1);
  }
  if ((count - 1) % 16 === 8) {
    toChange(x - 1, y + 1);
  }
  if ((count - 1) % 16 === 9) {
    toChange(x - 1, y);
  }
  if ((count - 1) % 16 === 10) {
    toChange(x - 1, y - 1);
  }
  if ((count - 1) % 16 === 11) {
    toChange(x, y - 1);
  }
  if ((count - 1) % 16 === 12) {
    toChange(x + 1, y - 1);
  }
  if ((count - 1) % 16 === 13) {
    toChange(x + 1, y);
  }
  if ((count - 1) % 16 === 14) {
    toChange(x + 1, y + 1);
  }
  if ((count - 1) % 16 === 15) {
    toChange(x, y + 1);
  }
  if (clearCount >= n * n) {
    return clear(stagenumber);
  }
};

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
    label[i][j + 3].addEventListener("touchstart", listener);
  }
}
