// Generated by CoffeeScript 1.3.3
var colorBackground, colorBorder, goalColor, i, j, mirrorFlag, num, startColor, _i, _j;

colorBorder = "#555";

colorBackground = "#5d8567";

startColor = "#85aa8e";

goalColor = "#855d7b";

num = 5;

mirrorFlag = 1;

Ti.include("property.js");

Ti.include("change.js");

Ti.include("label.js");

Ti.include("clear.js");

Ti.include("border.js");

Ti.include("tapCount.js");

Ti.include("toChange.js");

Ti.include("reset.js");

Ti.include("toTitle.js");

for (i = _i = 0; 0 <= num ? _i < num : _i > num; i = 0 <= num ? ++_i : --_i) {
  for (j = _j = 0; 0 <= num ? _j < num : _j > num; j = 0 <= num ? ++_j : --_j) {
    if (label[i][j].addEventListener) {
      label[i][j].addEventListener("touchstart", function(e) {
        var k, l, _k, _l;
        tapCountLabel.text++;
        for (k = _k = 0; 0 <= num ? _k < num : _k > num; k = 0 <= num ? ++_k : --_k) {
          for (l = _l = 0; 0 <= num ? _l < num : _l > num; l = 0 <= num ? ++_l : --_l) {
            if (this === label[k][l]) {
              toChange(k, l, k + 1, l, k + 2, l, k + 3, l, k + 2, l - 1);
            }
          }
        }
        if (clearCount >= num * num) {
          return clear();
        }
      });
    }
  }
}
