// Generated by CoffeeScript 1.6.3
var borderType, changeFlag, goalColor, i, j, labelColor, listener, mirrorFlag, n, stagenumber, startColor, _i, _j;

title.backgroundColor = "#ed8b9b";

startColor = "#8beddd";

goalColor = "#f4b7c1";

labelColor = "#6CB7AB";

stagenumber = 2;

n = 5;

mirrorFlag = 0;

borderType = 1;

changeFlag = 0;

Ti.include("property.js");

listener = function() {
  var k, x, y, _i, _ref, _ref1;
  _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
  for (k = _i = 0, _ref1 = n - x; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; k = 0 <= _ref1 ? ++_i : --_i) {
    toChange(x + k, y - k);
  }
  if (clearCount >= n * n) {
    return clear(stagenumber);
  }
};

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
    label[i][j + 3].addEventListener("touchstart", listener);
  }
}
