// Generated by CoffeeScript 1.6.3
var borderType, changeFlag, goalColor, i, j, labelColor, listener, mirrorFlag, n, stagenumber, startColor, _i, _j;

title.backgroundColor = "#b7f4b7";

labelColor = "#f4b7b7";

startColor = "#fbcfcf";

goalColor = "#fcfbe3";

n = 5;

stagenumber = 9;

mirrorFlag = 1;

borderType = 0;

changeFlag = 1;

Ti.include("property.js");

listener = function() {
  var x, y, _ref, _ref1, _ref2, _ref3, _ref4;
  _ref = [getX(this), getY(this)], x = _ref[0], y = _ref[1];
  if ((0 <= (_ref1 = (count - 1) % 8) && _ref1 < 2)) {
    toChange(x - 1, y);
  }
  if ((2 <= (_ref2 = (count - 1) % 8) && _ref2 < 4)) {
    toChange(x + 1, y);
  }
  if ((4 <= (_ref3 = (count - 1) % 8) && _ref3 < 6)) {
    toChange(x, y - 1);
  }
  if ((6 <= (_ref4 = (count - 1) % 8) && _ref4 < 8)) {
    toChange(x, y + 1);
  }
  if (clearCount >= n * n) {
    return clear(stagenumber);
  }
};

for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
  for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
    label[i][j + 3].addEventListener("touchstart", listener);
  }
}
