// Generated by CoffeeScript 1.6.3
var i, j, timerID, timerLabel, _i, _j;

if (lflag === 0) {
  timerLabel = Ti.UI.createLabel({
    flag: 0,
    text: "00:00",
    color: goalColor,
    font: {
      fontSize: deviceWidth / 12
    },
    width: Ti.UI.SIZE,
    height: Ti.UI.SIZE,
    right: deviceHeight / 12,
    top: (deviceHeight - deviceWidth) / 12,
    backgroundColor: colorBackground,
    opacity: 1.0
  });
  view.add(timerLabel);
  timerID = 0;
}

timerLabel.flag = 0;

for (i = _i = 0; _i < 5; i = ++_i) {
  for (j = _j = 0; _j < 5; j = ++_j) {
    label[i][j + 3].addEventListener("touchstart", function(e) {
      var datet, hour, min, now, sec, start;
      if (timerLabel.flag === 0) {
        timerLabel.flag = 1;
        start = new Date();
        hour = 0;
        min = 0;
        sec = 0;
        now = 0;
        datet = 0;
        return timerID = setInterval((function() {
          now = new Date();
          datet = parseInt((now.getTime() - start.getTime()) / 1000);
          hour = parseInt(datet / 3600);
          min = parseInt((datet / 60) % 60);
          sec = datet % 60;
          if (hour < 10) {
            hour = "0" + hour;
          }
          if (min < 10) {
            min = "0" + min;
          }
          if (sec < 10) {
            sec = "0" + sec;
          }
          return timerLabel.text = "" + min + ":" + sec;
        }), 1000);
      }
    });
  }
}

timerLabel.color = goalColor;

timerLabel.backgroundColor = title.backgroundColor;
