// Generated by CoffeeScript 1.6.3
var titleButton;

if (lflag === 0) {
  titleButton = Ti.UI.createLabel({
    text: "←",
    font: {
      fontSize: deviceWidth / 6
    },
    color: goalColor,
    top: -20,
    left: 0,
    width: deviceWidth / 4,
    height: (deviceHeight - deviceWidth) / 2,
    textAlign: "center",
    verticalAlign: "TEXT_VERTICAL_ALIGNMENT_CENTER",
    backgroundColor: colorBackground,
    opacity: 1.0
  });
  titleButton.addEventListener("touchstart", function(e) {
    var i, j, _i, _j, _k, _results;
    clearInterval(timerID);
    stagelabel.opacity = 0.0;
    resetButton.opacity = 0.0;
    titleButton.opacity = 0.0;
    tapCountLabel.opacity = 0.0;
    timerLabel.opacity = 0.0;
    timerLabel.text = "00:00";
    tapCountLabel.text = 0;
    clearCount *= 0;
    timerLabel.flag = 0;
    for (i = _i = 0; _i < 5; i = ++_i) {
      for (j = _j = 0; _j < 5; j = ++_j) {
        label[i][j + 3].removeEventListener("touchstart", listener);
        label[i][j + 3].flag = 0;
      }
    }
    _results = [];
    for (i = _k = 0; _k < 6; i = ++_k) {
      _results.push((function() {
        var _l, _results1;
        _results1 = [];
        for (j = _l = 0; _l < 9; j = ++_l) {
          label[i][j].borderWidth = deviceWidth / 96;
          if (Ti.Platform.osname === "android") {
            label[i][j].bottom = (deviceWidth / 3) * (3 - i);
            label[i][j].left = (deviceWidth / 3) * j;
            label[i][j].width = deviceWidth / 3;
            _results1.push(label[i][j].height = deviceWidth / 3);
          } else {
            _results1.push(label[i][j].animate({
              bottom: (deviceWidth / 3) * (3 - i),
              left: (deviceWidth / 3) * j,
              width: deviceWidth / 3,
              height: deviceWidth / 3
            }));
          }
        }
        return _results1;
      })());
    }
    return _results;
  });
  view.add(titleButton);
} else {
  titleButton.color = goalColor;
  titleButton.backgroundColor = title.backgroundColor;
}
